a=int(input("Enter first Number : "))
b=int(input("Enter Second Number : "))
print("-------------- Calculation ------------")
print("Addition : ",a+b)
print("Substration : ",a-b)
print("Multiplication : ",a*b)
print("Division : ",a/b)
print("Exponentiation : ",a**b)
print("Rounded Division : ",a//b)
